{
    "aikido": [
        {
            "name": "katatetori",
            "japanese": "片手取り",
            "waza": [
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "shihonage",
                    "name_alt": "",
                    "japanese": "四方投げ",
                    "id": 1,
                    "technique_type": "projection",
                    "direction": "omote",
                    "rank": "6th kyu",
                    "notes": "",
                    "translation": "",
                    "foot_movement": "step offline",
                    "hand_movement": "chudan grab",
                    "youtube_id": "_MPwI4RmHeU&t=5m12s"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "shihonage",
                    "name_alt": "",
                    "japanese": "四方投げ",
                    "id": 2,
                    "technique_type": "projection",
                    "direction": "tenkan",
                    "rank": "6th kyu",
                    "notes": "",
                    "translation": "",
                    "foot_movement": "step offline",
                    "hand_movement": "chudan grab",
                    "youtube_id": "_MPwI4RmHeU&t=7m12s"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kokyunage",
                    "name_alt": "inside spiral",
                    "japanese": "呼吸投げ",
                    "id": 4,
                    "technique_type": "projection",
                    "direction": "",
                    "rank": "5th kyu",
                    "notes": "",
                    "translation": "",
                    "foot_movement": "none",
                    "hand_movement": "jodan kokyu",
                    "youtube_id": "aiS6LPv06Xs"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name_alt": "kokyunage",
                    "name": "udekimenage",
                    "japanese": "呼吸投げ",
                    "id": 8,
                    "technique_type": "projection",
                    "direction": "tenkan",
                    "rank": "4th kyu",
                    "notes": "Tenzan name: jujinage",
                    "translation": "",
                    "foot_movement": "step offline",
                    "hand_movement": "chudan grab",
                    "youtube_id": "X5mL7Fy3i6w&t=52s"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 10,
                    "technique_type": "projection",
                    "direction": "tenkan",
                    "rank": "5th kyu",
                    "notes": "into forward roll",
                    "translation": "",
                    "foot_movement": "step offline",
                    "hand_movement": "chudan kokyu",
                    "youtube_id": "LJzwh22prCo"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "iriminage",
                    "name_alt": "",
                    "japanese": "入身投げ",
                    "id": 14,
                    "technique_type": "projection",
                    "direction": "tenkan",
                    "rank": "6th kyu",
                    "notes": "jodan",
                    "translation": "",
                    "foot_movement": "step offline",
                    "hand_movement": "gedan cut",
                    "youtube_id": "Kt6ROzf02cI&t=5s"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "nikyo",
                    "name_alt": "",
                    "japanese": "二教",
                    "id": 15,
                    "technique_type": "immobilization",
                    "direction": "",
                    "rank": "4th kyu",
                    "notes": "",
                    "translation": "",
                    "foot_movement": "step offline",
                    "hand_movement": "jodan atemi",
                    "youtube_id": "ummLn3M_Sk8&t=1m7s"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kotegaeshi",
                    "name_alt": "",
                    "japanese": "小手返し",
                    "id": 19,
                    "technique_type": "projection",
                    "direction": "tenkan",
                    "rank": "6th kyu",
                    "notes": "basic",
                    "translation": "",
                    "foot_movement": "step offline",
                    "hand_movement": "gedan cut",
                    "youtube_id": "O5ozbOKbl68"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "ikkyo",
                    "name_alt": "swooping move",
                    "japanese": "一教",
                    "id": 25,
                    "technique_type": "immobilization",
                    "direction": "omote",
                    "rank": "5th kyu",
                    "notes": "tenzan style(?)",
                    "translation": "",
                    "foot_movement": "step offline",
                    "hand_movement": "chudan cut",
                    "youtube_id": "1XlhMk5nvGU"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 31,
                    "technique_type": "projection",
                    "direction": "tenkan",
                    "rank": "*",
                    "notes": "Yamada style - bring uke around as you drop, then extend past uke's head",
                    "translation": "",
                    "foot_movement": "step offline",
                    "hand_movement": "jodan kokyu",
                    "youtube_id": "Kt6ROzf02cI&t=45s"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kaitennage",
                    "name_alt": "",
                    "japanese": "回転投げ",
                    "id": 28,
                    "technique_type": "projection",
                    "direction": "",
                    "rank": "4th kyu",
                    "notes": "offline irimi",
                    "translation": "",
                    "foot_movement": "step offline",
                    "hand_movement": "gedan kokyu",
                    "youtube_id": "gqvZ4KzIESw&t=21s"
                }
            ]
        }
    ]
}