{
    "katatedori": [
        {
            "core": [
                {
                    "attack_type": "katatedori",
                    "name": "shihonage",
                    "name_alt": "",
                    "id": 6,
                    "technique_type": "projection",
                    "direction": "omote",
                    "rank": "6th kyu",
                    "notes": "",
                    "foot_movement": "offline step",
                    "hand_movement": "gedan grab",
                    "posture": "",
                    "youtube_id": "_MPwI4RmHeU&t=5m12s"
                },
                {
                    "attack_type": "katatedori",
                    "name": "shihonage",
                    "name_alt": "",
                    "japanese": "四方投げ",
                    "id": 6,
                    "technique_type": "projection",
                    "direction": "ura",
                    "rank": "6th kyu",
                    "notes": "tenkan",
                    "foot_movement": "offline step",
                    "hand_movement": "gedan grab",
                    "posture": "",
                    "youtube_id": "_MPwI4RmHeU&t=7m12s"
                },
                {
                    "attack_type": "katatedori",
                    "name": "kotegaeshi",
                    "name_alt": "",
                    "japanese": "小手返し",
                    "id": 7,
                    "technique_type": "projection",
                    "direction": "ura",
                    "rank": "6th kyu",
                    "notes": "basic – tenkan",
                    "foot_movement": "offline step",
                    "hand_movement": "cut across",
                    "posture": "",
                    "youtube_id": "O5ozbOKbl68"
                },
                {
                    "attack_type": "katatedori",
                    "name": "iriminage",
                    "name_alt": "",
                    "japanese": "入身投げ",
                    "id": 8,
                    "technique_type": "projection",
                    "direction": "ura",
                    "rank": "6th kyu",
                    "notes": "jodan – tenkan",
                    "foot_movement": "offline step",
                    "hand_movement": "cut across",
                    "posture": "",
                    "youtube_id": "Kt6ROzf02cI&t=5s"
                },

                {
                    "attack_type": "katatedori",
                    "name": "ikkyo",
                    "name_alt": "",
                    "japanese": "一教",
                    "id": 10,
                    "technique_type": "immobilization",
                    "direction": "omote / ura",
                    "rank": "5th kyu",
                    "notes": "",
                    "foot_movement": "offline step",
                     "hand_movement": "circular, swooping move",
                    "posture": "",
                    "youtube_id": "1XlhMk5nvGU"
                },
                {
                    "attack_type": "katatedori",
                    "name": "kokyunage into to forward roll",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 20,
                    "technique_type": "projection",
                    "direction": "uchi mawari",
                    "rank": "5th kyu",
                    "notes": "tenkan",
                    "foot_movement": "offline step",
                     "hand_movement": "*open the door",
                    "posture": "",
                    "youtube_id": "LJzwh22prCo"
                },
                {
                    "attack_type": "katatedori",
                    "name": "kaitennage",
                    "name_alt": "",
                    "japanese": "回転投げ",
                    "id": 20,
                    "technique_type": "projection",
                    "direction": "uchi mawari",
                    "rank": "3th kyu",
                    "notes": "irimi tenkan",
                    "foot_movement": "offline step",
                     "hand_movement": "*open the door",
                    "posture": "",
                    "youtube_id": "gqvZ4KzIESw&t=21s"
                },
                {
                    "attack_type": "katatedori",
                    "name": "kaitennage",
                    "name_alt": "",
                    "japanese": "回転投げ",
                    "id": 20,
                    "technique_type": "projection",
                    "direction": "soto mawari",
                    "rank": "3th kyu",
                    "notes": "irimi tenkan",
                    "foot_movement": "offline step",
                     "hand_movement": "*answer the phone",
                    "posture": "",
                    "youtube_id": "gqvZ4KzIESw&t=21s"
                },
                {
                    "attack_type": "katatedori",
                    "name": "nikyo",
                    "name_alt": "",
                    "japanese": "二教",
                    "id": 21,
                    "technique_type": "immobilization",
                    "direction": "omote / ura",
                    "rank": "4th kyu",
                    "notes": "",
                    "foot_movement": "offline step",
                    "hand_movement": "circular, swooping move",
                    "posture": "",
                    "youtube_id": "ummLn3M_Sk8&t=1m7s"
                },
                {
                    "attack_type": "katatedori",
                    "name": "sankyo",
                    "name_alt": "",
                    "japanese": "三教",
                    "id": 128,
                    "technique_type": "projection",
                    "direction": "omote / ura",
                    "rank": "1st dan",
                    "notes": "Yamada style",
                    "foot_movement": "offline step",
                     "hand_movement": "circular, swooping move",
                    "posture": "",
                    "youtube_id": "Kt6ROzf02cI"
                },
                {
                    "attack_type": "katatedori",
                    "name": "kokyunage - inside spiral",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 34,
                    "technique_type": "projection",
                    "direction": "omote",
                    "rank": "3th kyu",
                    "notes": "",
                    "foot_movement": "none",
                    "hand_movement": "spiral up",
                    "posture": "",
                    "youtube_id": "aiS6LPv06Xs"
                },
                {
                    "attack_type": "katatedori",
                    "name": "kokyunage - inside spiral",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 34,
                    "technique_type": "projection",
                    "direction": "ura",
                    "rank": "3th kyu",
                    "notes": "",
                    "foot_movement": "step back",
                    "hand_movement": "spiral up",
                    "posture": "",
                    "youtube_id": "aiS6LPv06Xs"
                },
                {
                    "attack_type": "katatedori",
                    "name": "koshinage",
                    "name_alt": "",
                    "japanese": "腰投げ",
                    "id": 35,
                    "technique_type": "projection",
                    "direction": "",
                    "rank": "3rd kyu",
                    "notes": "atemi as you step inside and turn, making a chair of your lower back to lower uke over",
                    "foot_movement": "inside step",
                     "hand_movement": "reach up",
                    "posture": "",
                    "youtube_id": "Kt6ROzf02cI&t=3m6s"
                },
                {
                    "attack_type": "katatedori",
                    "name": "kokyunage – sumiotoshi (drop to knees)",
                    "name_alt": "",
                    "japanese": "",
                    "id": 99,
                    "technique_type": "projection",
                    "direction": "uchi mawari",
                    "rank": "1st kyu",
                    "notes": "irimi tenkan",
                    "foot_movement": "offline step",
                     "hand_movement": "*open the door",
                    "posture": "",
                    "youtube_id": "gqvZ4KzIESw&t=21s"
                },
                {
                    "attack_type": "katatedori",
                    "name": "kokyunage – into forward roll",
                    "name_alt": "",
                    "japanese": "",
                    "id": 20,
                    "technique_type": "projection",
                    "direction": "soto mawari",
                    "rank": "1st kyu",
                    "notes": "irimi tenkan",
                    "foot_movement": "offline step",
                     "hand_movement": "*answer the phone",
                    "posture": "",
                    "youtube_id": "gqvZ4KzIESw&t=21s"
                },
                {
                    "attack_type": "katatedori",
                    "name": "kokyunage – reverse *kesa*",
                    "name_alt": "",
                    "japanese": "",
                    "id": 20,
                    "technique_type": "projection",
                    "direction": "uchi mawari",
                    "rank": "1st kyu",
                    "notes": "irimi tenkan",
                    "foot_movement": "offline step",
                     "hand_movement": "*open the door",
                    "posture": "",
                    "youtube_id": "gqvZ4KzIESw&t=21s"
                },
                {
                    "attack_type": "katatedori",
                    "name": "kokyunage – tenkan and kneel down",
                    "name_alt": "",
                    "japanese": "",
                    "id": 101,
                    "technique_type": "projection",
                    "direction": "ura",
                    "rank": "1st kyu",
                    "notes": "Yamada style - bring uke around as you drop, then extend past uke's head",
                    "foot_movement": "offline step",
                     "hand_movement": "reach down",
                    "posture": "",
                    "youtube_id": "Kt6ROzf02cI&t=45s"
                },
                {
                    "attack_type": "katatedori",
                    "name": "katagatame",
                    "name_alt": "",
                    "japanese": "回転投げ",
                    "id": 102,
                    "technique_type": "projection",
                    "direction": "uchi mawari",
                    "rank": "1st kyu",
                    "notes": "irimi tenkan",
                    "foot_movement": "offline step",
                     "hand_movement": "*open the door",
                    "posture": "",
                    "youtube_id": "gqvZ4KzIESw&t=21s"
                },
                {
                    "attack_type": "katatedori",
                    "name": "katagatame",
                    "name_alt": "",
                    "japanese": "回転投げ",
                    "id": 102,
                    "technique_type": "projection",
                    "direction": "soto mawari",
                    "rank": "1st kyu",
                    "notes": "irimi tenkan",
                    "foot_movement": "offline step",
                     "hand_movement": "*answer the phone",
                    "posture": "",
                    "youtube_id": "gqvZ4KzIESw&t=21s"
                },
                {
                    "attack_type": "katatedori",
                    "name": "shihonage – ki no nagare – Jo",
                    "name_alt": "",
                    "japanese": "?落し",
                    "id": 103,
                    "technique_type": "projection",
                    "direction": "",
                    "rank": "1st kyu",
                    "notes": "Jodan Kazushi",
                    "foot_movement": "tenshin",
                    "hand_movement": "jodan grab",
                    "posture": "",
                    "youtube_id": ""
                },
                {
                    "attack_type": "katatedori",
                    "name": "shihonage – ki no nagare – chu",
                    "name_alt": "",
                    "japanese": "?落し",
                    "id": 103,
                    "technique_type": "projection",
                    "direction": "",
                    "rank": "1st kyu",
                    "notes": "chu kazushi",
                    "foot_movement": "tenshin",
                    "hand_movement": "chudan grab",
                    "posture": "",
                    "youtube_id": ""
                },
                {
                    "attack_type": "katatedori",
                    "name": "shihonage – ki no nagare - ge",
                    "name_alt": "",
                    "japanese": "?落し",
                    "id": 103,
                    "technique_type": "projection",
                    "direction": "",
                    "rank": "1st kyu",
                    "notes": "ge kazushi",
                    "foot_movement": "tenshin",
                    "hand_movement": "gedan grab",
                    "posture": "",
                    "youtube_id": ""
                },
                {
                    "attack_type": "katatedori",
                    "name": "nikyo – ki no nagare",
                    "name_alt": "",
                    "japanese": "二教",
                    "id": 104,
                    "technique_type": "immobilization",
                    "direction": "",
                    "rank": "1st kyu",
                    "notes": "",
                    "foot_movement": "tenshin",
                     "hand_movement": "gedan grab",
                    "posture": "",
                    "youtube_id": "-xj11RYo7Vg"
                },
                {
                    "attack_type": "katatedori",
                    "name": "kokyunage – draping move",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 137,
                    "technique_type": "projection",
                    "direction": "",
                    "rank": "1st kyu",
                    "notes": "",
                    "foot_movement": "ayumi ashi",
                    "hand_movement": "draping",
                    "posture": "",
                    "youtube_id": "Kt6ROzf02cI&t=35s"
                },
                {
                    "attack_type": "katatedori",
                    "name": "kokyunage – aikiotoshi",
                    "name_alt": "",
                    "id": 138,
                    "technique_type": "projection",
                    "direction": "omote",
                    "rank": "1st kyu",
                    "notes": "",
                    "foot_movement": "offline step",
                    "hand_movement": "gedan grab",
                    "posture": "",
                    "youtube_id": "_MPwI4RmHeU&t=5m12s"
                },
                {
                    "attack_type": "katatedori",
                    "name": "kokyunage – hijinage",
                    "name_alt": "arm bar",
                    "japanese": "?",
                    "id": 138,
                    "technique_type": "projection",
                    "direction": "",
                    "rank": "1st kyu",
                    "notes": "step to the side and lower the grabbed hand, while bracing uke's elbow with the other",
                    "foot_movement": "offline step",
                     "hand_movement": "hug elbow",
                    "posture": "",
                    "youtube_id": "mjbZDCkIZeU&t=2m32s"
                },
                {
                    "attack_type": "katatedori",
                    "name": "reverse kotegaeshi",
                    "name_alt": "",
                    "japanese": "小手返し",
                    "id": 139,
                    "technique_type": "projection",
                    "direction": "",
                    "rank": "2nd kyu",
                    "notes": "",
                    "foot_movement": "tenshin",
                    "posture": "",
                    "hand_movement": "jodan grab",
                    "youtube_id": "Gw6hSmZ9WHY&t=8s"
                },
                {
                    "attack_type": "katatedori",
                    "name": "kokyunage – choke",
                    "name_alt": "Nishio's Choke",
                    "japanese": "一教",
                    "id": 137,
                    "technique_type": "immobilization",
                    "direction": "soto mawari",
                    "rank": "1st dan",
                    "notes": "starts like kaitennage then spin uke for a choke",
                    "foot_movement": "offline step",
                     "hand_movement": "*answer the phone",
                    "posture": "",
                    "youtube_id": ""
                }
            ],
            "kokyunage": [
                {
                    "attack_type": "katatedori",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 13,
                    "technique_type": "projection",
                    "direction": "",
                    "rank": "1st kyu",
                    "notes": "reach down diagonally in front of uke and drop",
                    "foot_movement": "turn inside",
                     "hand_movement": "gedan kokyu",
                    "posture": "",
                    "youtube_id": ""
                },
                {
                    "attack_type": "katatedori",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 15,
                    "technique_type": "projection",
                    "direction": "ki no nagare",
                    "rank": "3rd kyu",
                    "notes": "direct entry: quickly extend past uke head",
                    "foot_movement": "offline step",
                     "hand_movement": "jodan kokyu",
                    "posture": "",
                    "youtube_id": ""
                }
            ],
            "variations": [
                
                {
                    "attack_type": "katatedori",
                    "name": "iriminage",
                    "name_alt": "",
                    "japanese": "?落し",
                    "id": 34,
                    "technique_type": "projection",
                    "direction": "",
                    "rank": "1st kyu",
                    "notes": "step back and cut at uke's elbow then enter behind",
                    "foot_movement": "tenshin",
                     "hand_movement": "gedan cut",
                    "posture": "",
                    "youtube_id": ""
                },
                {
                    "attack_type": "katatedori – ki no nagare",
                    "name": "kokyunage – makiotoshi",
                    "name_alt": "",
                    "japanese": "?落し",
                    "id": 32,
                    "technique_type": "projection",
                    "direction": "",
                    "rank": "1st kyu",
                    "notes": "",
                    "foot_movement": "tenshin",
                    "hand_movement": "gedan kokyu",
                    "posture": "",
                    "youtube_id": "VtjNiohlH5Q"
                },
                {
                    "attack_type": "katatedori",
                    "name": "sumiotoshi",
                    "name_alt": "",
                    "japanese": "角落し",
                    "id": 18,
                    "technique_type": "projection",
                    "direction": "tenkan",
                    "rank": "2nd kyu",
                    "notes": "",
                    "foot_movement": "offline step",
                    "hand_movement": "chudan kokyu",
                    "posture": "",
                    "youtube_id": "zDgjNFsVq6Y&t=8s"
                },

                {
                    "attack_type": "katatedori",
                    "name": "sumiotoshi",
                    "name_alt": "",
                    "japanese": "角落し",
                    "id": 19,
                    "technique_type": "projection",
                    "direction": "irimi",
                    "rank": "2nd kyu",
                    "notes": "",
                    "foot_movement": "offline step",
                    "hand_movement": "gedan kokyu",
                    "posture": "",
                    "youtube_id": "m9qyncOTzRg"
                },
                {
                    "attack_type": "katatedori",
                    "name": "kokyunage",
                    "name_alt": "sumiotoshi-like",
                    "japanese": "呼吸投げ",
                    "id": 17,
                    "technique_type": "projection",
                    "direction": "offline irimi",
                    "rank": "1st kyu",
                    "notes": "extend hand down and behind uke, to unballance them into back roll / breakfall",
                    "foot_movement": "offline step",
                     "hand_movement": "gedan kokyu",
                    "posture": "",
                    "youtube_id": "KyRnlnk4dU4"
                },
                {
                    "attack_type": "katatedori",
                    "name": "ikkyo",
                    "name_alt": "",
                    "japanese": "一教",
                    "id": 26,
                    "technique_type": "immobilization",
                    "direction": "tenkan",
                    "rank": "5th kyu",
                    "notes": "Yamada style",
                    "foot_movement": "offline step",
                     "hand_movement": "chudan kokyu",
                    "posture": "",
                    "youtube_id": "Kt6ROzf02cI&t=1m"
                },
                {
                    "attack_type": "katatedori",
                    "name": "nikyo",
                    "name_alt": "",
                    "japanese": "",
                    "id": 27,
                    "technique_type": "immobilization",
                    "direction": "tenkan",
                    "rank": "1st kyu",
                    "notes": "Yamada style",
                    "foot_movement": "offline step",
                     "hand_movement": "chudan kokyu",
                    "posture": "",
                    "youtube_id": "Kt6ROzf02cI&t=1m17s"
                }
            ],
            "other": [
                {
                    "attack_type": "katatedori",
                    "name_alt": "kokyunage",
                    "name": "udekimenage",
                    "japanese": "呼吸投げ",
                    "id": 4,
                    "technique_type": "projection",
                    "direction": "tenkan",
                    "rank": "4th kyu",
                    "notes": "Tenzan name: jujinage",
                    "foot_movement": "offline step",
                     "hand_movement": "gedan grab",
                    "posture": "",
                    "youtube_id": "X5mL7Fy3i6w&t=52s"
                },
                {
                    "attack_type": "katatedori",
                    "name": "kokyunage - ushiro ate",
                    "name_alt": "",
                    "japanese": "?",
                    "id": 25,
                    "technique_type": "projection",
                    "direction": "tenkan",
                    "rank": "2nd kyu",
                    "notes": "",

                    "foot_movement": "offline step",
                    "posture": "",
                    "hand_movement": "gedan cut",
                    "youtube_id": ""
                }
            ],
            "hanmi_handachi": [
                {
                    "attack_type": "katatedori",
                    "name": "shihonage",
                    "name_alt": "",
                    "id": 36,
                    "technique_type": "projection",
                    "direction": "omote",
                    "rank": "3th kyu",
                    "notes": "",
                    "foot_movement": "inside step",
                    "hand_movement": "gedan grab",
                    "posture": "Hanmi handachi",
                    "youtube_id": "_MPwI4RmHeU&t=5m12s"
                },
                {
                    "attack_type": "katatedori",
                    "name": "shihonage",
                    "name_alt": "",
                    "japanese": "四方投げ",
                    "id": 36,
                    "technique_type": "projection",
                    "direction": "ura",
                    "rank": "3th kyu",
                    "notes": "tenkan",
                    "foot_movement": "offline step",
                    "hand_movement": "gedan grab",
                    "posture": "Hanmi handachi",
                    "youtube_id": "_MPwI4RmHeU&t=7m12s"
                }
            ]
        }
    ]
}