{
    "shomenuchi": [
        {
            "core": [
                {
                    "attack_type": "shomenuchi",
                    "name": "ikkyo",
                    "name_alt": "",
                    "id": 12,
                    "technique_type": "imobilisation",
                    "direction": "omote",
                    "rank": "6th kyu",
                    "notes": "",
                    "foot_movement": "ayumi ashi",
                    "hand_movement": "ikkyo",
                    "posture": "",
                    "youtube_id": ""
                },
                {
                    "attack_type": "shomenuchi",
                    "name": "ikkyo",
                    "name_alt": "",
                    "id": 12,
                    "technique_type": "imobilisation",
                    "direction": "ura",
                    "rank": "6th kyu",
                    "notes": "",
                    "foot_movement": "offline step",
                    "hand_movement": "ikkyo",
                    "posture": "",
                    "youtube_id": ""
                },
                {
                    "attack_type": "shomenuchi",
                    "name": "iriminage",
                    "name_alt": "",
                    "id": 13,
                    "technique_type": "projection",
                    "direction": "irimi tenkan",
                    "rank": "6th kyu",
                    "notes": "",
                    "foot_movement": "offline step",
                    "hand_movement": "meet the attack",
                    "posture": "",
                    "youtube_id": ""
                },
                {
                    "attack_type": "shomenuchi",
                    "name": "kotegaeshi",
                    "name_alt": "",
                    "id": 14,
                    "technique_type": "projection",
                    "direction": "tenkan",
                    "rank": "6th kyu",
                    "notes": "",
                    "foot_movement": "offline step",
                    "hand_movement": "meet the attack",
                    "posture": "",
                    "youtube_id": ""
                },
                {
                    "attack_type": "shomenuchi",
                    "name": "nikyo",
                    "name_alt": "",
                    "id": 22,
                    "technique_type": "imobilisation",
                    "direction": "omote",
                    "rank": "4th kyu",
                    "notes": "",
                    "foot_movement": "ayumi ashi",
                    "hand_movement": "ikkyo",
                    "posture": "",
                    "youtube_id": ""
                },
                {
                    "attack_type": "shomenuchi",
                    "name": "nikyo",
                    "name_alt": "",
                    "id": 22,
                    "technique_type": "imobilisation",
                    "direction": "ura",
                    "rank": "4th kyu",
                    "notes": "",
                    "foot_movement": "offline step",
                    "hand_movement": "cutting",
                    "posture": "",
                    "youtube_id": ""
                },
                {
                    "attack_type": "shomenuchi",
                    "name": "kaitennage",
                    "name_alt": "",
                    "id": 23,
                    "technique_type": "projection",
                    "direction": "ura",
                    "rank": "4th kyu",
                    "notes": "",
                    "foot_movement": "offline step",
                    "hand_movement": "cut down",
                    "posture": "",
                    "youtube_id": ""
                },
                {
                    "attack_type": "shomenuchi",
                    "name": "sankyo",
                    "name_alt": "",
                    "id": 38,
                    "technique_type": "imobilisation",
                    "direction": "omote",
                    "rank": "3rd kyu",
                    "notes": "",
                    "foot_movement": "ayumi ashi",
                    "hand_movement": "ikkyo",
                    "posture": "",
                    "youtube_id": ""
                },
                {
                    "attack_type": "shomenuchi",
                    "name": "sankyo",
                    "name_alt": "",
                    "id": 38,
                    "technique_type": "imobilisation",
                    "direction": "ura",
                    "rank": "3rd kyu",
                    "notes": "",
                    "foot_movement": "offline step",
                    "hand_movement": "cutting",
                    "posture": "",
                    "youtube_id": ""
                },
                {
                    "attack_type": "shomenuchi",
                    "name": "yonkyo",
                    "name_alt": "",
                    "id": 39,
                    "technique_type": "imobilisation",
                    "direction": "omote",
                    "rank": "3rd kyu",
                    "notes": "",
                    "foot_movement": "ayumi ashi",
                    "hand_movement": "ikkyo",
                    "posture": "",
                    "youtube_id": ""
                },
                {
                    "attack_type": "shomenuchi",
                    "name": "yonkyo",
                    "name_alt": "",
                    "id": 39,
                    "technique_type": "imobilisation",
                    "direction": "ura",
                    "rank": "3rd kyu",
                    "notes": "",
                    "foot_movement": "offline step",
                    "hand_movement": "cutting",
                    "posture": "",
                    "youtube_id": ""
                },
                {
                    "attack_type": "shomenuchi",
                    "name": "gokyo",
                    "name_alt": "",
                    "id": 63,
                    "technique_type": "projection",
                    "direction": "ura",
                    "rank": "2nd kyu",
                    "notes": "bop then grab – *guitar grip*",
                    "foot_movement": "offline step",
                    "hand_movement": "strike *above* elbow",
                    "posture": "",
                    "youtube_id": ""
                },
                {
                    "attack_type": "shomenuchi",
                    "name": "kokyunage – kesa-based",
                    "name_alt": "",
                    "id": 65,
                    "technique_type": "projection",
                    "direction": "omote",
                    "rank": "2nd kyu",
                    "notes": "",
                    "foot_movement": "inside step",
                    "hand_movement": "kesa cut",
                    "posture": "",
                    "youtube_id": ""
                },
                {
                    "attack_type": "shomenuchi",
                    "name": "kokyunage – pull bow apart",
                    "name_alt": "",
                    "id": 66,
                    "technique_type": "projection",
                    "direction": "irimi",
                    "rank": "2nd kyu",
                    "notes": "",
                    "foot_movement": "step forward",
                    "hand_movement": "*x* shape",
                    "posture": "",
                    "youtube_id": ""
                },
                {
                    "attack_type": "shomenuchi",
                    "name": "kokyunage – pull bow apart",
                    "name_alt": "",
                    "id": 66,
                    "technique_type": "projection",
                    "direction": "irimi",
                    "rank": "2nd kyu",
                    "notes": "",
                    "foot_movement": "slide forward",
                    "hand_movement": "*x* shape",
                    "posture": "",
                    "youtube_id": ""
                },
                {
                    "attack_type": "shomenuchi",
                    "name": "shihonage",
                    "name_alt": "",
                    "id": 67,
                    "technique_type": "imobilisation",
                    "direction": "omote",
                    "rank": "2nd kyu",
                    "notes": "",
                    "foot_movement": "offline step",
                    "hand_movement": "circular cut",
                    "posture": "",
                    "youtube_id": ""
                },
                {
                    "attack_type": "shomenuchi",
                    "name": "shihonage",
                    "name_alt": "",
                    "id": 67,
                    "technique_type": "imobilisation",
                    "direction": "ura",
                    "rank": "2nd kyu",
                    "notes": "",
                    "foot_movement": "offline step",
                    "hand_movement": "circular cut",
                    "posture": "",
                    "youtube_id": ""
                },
                {
                    "attack_type": "shomenuchi",
                    "name": "koshinage – from ikkyo",
                    "name_alt": "",
                    "id": 68,
                    "technique_type": "projection",
                    "direction": "irimi",
                    "rank": "2nd kyu",
                    "notes": "",
                    "foot_movement": "inside step",
                    "hand_movement": "meet the attack",
                    "posture": "",
                    "youtube_id": ""
                }
            ],
            "other": []
        }
    ]
}