{
    "waza": {
        "katatetori": [
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "shihonage",
                "name_alt": "",
                "id": 1,
                "technique_type": "projection",
                "variation": "",
                "rank": "6th kyu",
                "notes": "",
                "translation": "",
                "opening": "step offline",
                "url": ""
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "shihonage",
                "name_alt": "",
                "id": 2,
                "technique_type": "projection",
                "variation": "",
                "rank": "6th kyu",
                "notes": "",
                "translation": "",
                "opening": "tenkan",
                "url": ""
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "kokyunage",
                "name_alt": "",
                "id": 3,
                "technique_type": "projection",
                "variation": "",
                "rank": "*",
                "notes": "reach down diagonally in front of uke and drop",
                "translation": "",
                "opening": "irimi",
                "url": ""
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "kokyunage",
                "name_alt": "",
                "id": 4,
                "technique_type": "projection",
                "variation": "inside spiral",
                "rank": "*",
                "notes": "",
                "translation": "",
                "opening": "irimi",
                "url": ""
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "kokyunage",
                "name_alt": "draping move",
                "id": 5,
                "technique_type": "projection",
                "variation": "draping move",
                "rank": "1st kyu",
                "notes": "",
                "translation": "",
                "opening": "step offline",
                "url": "http://www.youtube.com/watch?v=Kt6ROzf02cI"
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "kokyunage",
                "name_alt": "",
                "id": 6,
                "technique_type": "projection",
                "variation": "ki no nagare",
                "rank": "*",
                "notes": "step in and swoop uke's arm into yours as you break the grip, then extend past his head",
                "translation": "",
                "opening": "step offline",
                "url": ""
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "kokyunage",
                "name_alt": "kazaguruma",
                "id": 7,
                "technique_type": "projection",
                "variation": "double cut",
                "rank": "*",
                "notes": "",
                "translation": "",
                "opening": "step offline",
                "url": "http://www.youtube.com/watch?v=Kt6ROzf02cI"
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "kokyunage",
                "name_alt": "jujinage",
                "id": 8,
                "technique_type": "projection",
                "variation": "",
                "rank": "*",
                "notes": "",
                "translation": "",
                "opening": "tenkan",
                "url": ""
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "kokyunage",
                "name_alt": "",
                "id": 9,
                "technique_type": "projection",
                "variation": "into back roll / breakfall",
                "rank": "*",
                "notes": "extend hand down and behind uke, to unballance them",
                "translation": "",
                "opening": "offline irimi",
                "url": ""
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "kokyunage",
                "name_alt": "",
                "id": 10,
                "technique_type": "projection",
                "variation": "into forward roll",
                "rank": "5th kyu",
                "notes": "",
                "translation": "",
                "opening": "tenkan",
                "url": ""
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "kokyunage",
                "name_alt": "",
                "id": 11,
                "technique_type": "projection",
                "variation": "",
                "rank": "*",
                "notes": "like sumiotoshi into a forward roll",
                "translation": "corner drop",
                "opening": "switch feet",
                "url": ""
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "sumiotoshi",
                "name_alt": "",
                "id": 12,
                "technique_type": "projection",
                "variation": "",
                "rank": "2nd kyu",
                "notes": "",
                "translation": "corner drop",
                "opening": "tenkan",
                "url": ""
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "sumiotoshi",
                "name_alt": "",
                "id": 13,
                "technique_type": "projection",
                "variation": "",
                "rank": "2nd kyu",
                "notes": "",
                "translation": "corner drop",
                "opening": "offline irimi",
                "url": ""
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "iriminage",
                "name_alt": "",
                "id": 14,
                "technique_type": "projection",
                "variation": "jo",
                "rank": "6th kyu",
                "notes": "",
                "translation": "",
                "opening": "offline irimi",
                "url": "http://www.youtube.com/watch?v=Kt6ROzf02cI"
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "nikyo",
                "name_alt": "",
                "id": 15,
                "technique_type": "immobilization",
                "variation": "swooping move",
                "rank": "4th kyu",
                "notes": "",
                "translation": "",
                "opening": "step offline",
                "url": ""
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "nikyo",
                "name_alt": "",
                "id": 16,
                "technique_type": "immobilization",
                "variation": "w/ atemi",
                "rank": "*",
                "notes": "cut ukes arm at the elbow, as you step in place, then tenkan",
                "translation": "",
                "opening": "switch feet",
                "url": ""
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "nikyo",
                "name_alt": "",
                "id": 17,
                "technique_type": "immobilization",
                "variation": "",
                "rank": "4th kyu",
                "notes": "",
                "translation": "",
                "opening": "tenkan",
                "url": ""
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "kotegaeshi",
                "name_alt": "",
                "id": 18,
                "technique_type": "projection",
                "variation": "reverse kotegaeshi",
                "rank": "*",
                "notes": "",
                "translation": "",
                "opening": "switch feet",
                "url": ""
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "kotegaeshi",
                "name_alt": "",
                "id": 19,
                "technique_type": "projection",
                "variation": "",
                "rank": "6th kyu",
                "notes": "basic",
                "translation": "",
                "opening": "tenkan",
                "url": ""
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "koshinage",
                "name_alt": "",
                "id": 20,
                "technique_type": "projection",
                "variation": "",
                "rank": "3rd kyu",
                "notes": "atemi as you step inside and turn, making a chair of your lower back to lower uke over",
                "translation": "",
                "opening": "switch feet",
                "url": ""
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "hijikime",
                "name_alt": "",
                "id": 21,
                "technique_type": "immobilization",
                "variation": "swopping move",
                "rank": "*",
                "notes": "",
                "translation": "",
                "opening": "tenkan",
                "url": ""
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "hiji waza",
                "name_alt": "arm bar",
                "id": 22,
                "technique_type": "projection",
                "variation": "",
                "rank": "*",
                "notes": "step to the side and lower the grabbed hand, while bracing uke's elbow with the other",
                "translation": "",
                "opening": "step offline",
                "url": ""
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "ushiro ate",
                "name_alt": "",
                "id": 23,
                "technique_type": "projection",
                "variation": "",
                "rank": "*",
                "notes": "",
                "translation": "",
                "opening": "offline irimi",
                "url": ""
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "ikkyo",
                "name_alt": "",
                "id": 24,
                "technique_type": "immobilization",
                "variation": "",
                "rank": "5th kyu",
                "notes": "Yamada style",
                "translation": "",
                "opening": "tenkan",
                "url": "http://www.youtube.com/watch?v=Kt6ROzf02cI"
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "ikkyo",
                "name_alt": "",
                "id": 25,
                "technique_type": "immobilization",
                "variation": "swooping move",
                "rank": "5th kyu",
                "notes": "tenzan style(?)",
                "translation": "",
                "opening": "step offline",
                "url": ""
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "sankyo",
                "name_alt": "",
                "id": 26,
                "technique_type": "projection",
                "variation": "",
                "rank": "*",
                "notes": "Yamada style",
                "translation": "",
                "opening": "tenkan",
                "url": "http://www.youtube.com/watch?v=Kt6ROzf02cI"
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "katagatame",
                "name_alt": "",
                "id": 27,
                "technique_type": "immobilization",
                "variation": "",
                "rank": "1st kyu",
                "notes": "",
                "translation": "",
                "opening": "tenkan",
                "url": ""
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "kaitennage",
                "name_alt": "",
                "id": 28,
                "technique_type": "projection",
                "variation": "",
                "rank": "4th kyu",
                "notes": "",
                "translation": "",
                "opening": "offline irimi",
                "url": ""
            },
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "aikiotoshi",
                "name_alt": "",
                "id": 29,
                "technique_type": "projection",
                "variation": "",
                "rank": "*",
                "notes": "",
                "translation": "",
                "opening": "step offline",
                "url": ""
            }, 
            {
                "attack_type": "katatetori",
                "attack_variation": "gyaku hanmi",
                "name": "maki otoshi",
                "name_alt": "",
                "id": 30,
                "technique_type": "projection",
                "variation": "",
                "rank": "*",
                "notes": "",
                "translation": "",
                "opening": "step inside",
                "url": "https://www.youtube.com/watch?v=VtjNiohlH5Q"
            }
        ],
        "shomenuchi": [
            {
                "attack_type": "shomenuchi",
                "attack_variation": "",
                "name": "ikkyo",
                "name_alt": "",
                "id": 1,
                "technique_type": "immobilization",
                "variation": "omote",
                "rank": "5th kyu",
                "notes": "",
                "translation": "1st technique",
                "opening": "irimi",
                "url": ""
            },
            {
                "attack_type": "shomenuchi",
                "attack_variation": "",
                "name": "iriminage",
                "name_alt": "",
                "id": 2,
                "technique_type": "projection",
                "variation": "",
                "rank": "5th kyu",
                "notes": "",
                "translation": "",
                "opening": "offline irimi",
                "url": ""
            },
            {
                "attack_type": "shomenuchi",
                "attack_variation": "",
                "name": "nikyo",
                "name_alt": "",
                "id": 3,
                "technique_type": "immobilization",
                "variation": "ura",
                "rank": "4th kyu",
                "notes": "same opening as kaiten nage",
                "translation": "",
                "opening": "offline irimi",
                "url": ""
            },
            {
                "attack_type": "shomenuchi",
                "attack_variation": "",
                "name": "sankyo",
                "name_alt": "",
                "id": 4,
                "technique_type": "immobilization",
                "variation": "omote",
                "rank": "3rd kyu",
                "notes": "ikkyo opening – then switch to sankyo",
                "translation": "",
                "opening": "irimi",
                "url": ""
            },
            {
                "attack_type": "shomenuchi",
                "attack_variation": "",
                "name": "shihonage",
                "name_alt": "",
                "id": 5,
                "technique_type": "projection",
                "variation": "",
                "rank": "2nd kyu",
                "notes": "",
                "translation": "",
                "opening": "irimi",
                "url": ""
            },
            {
                "attack_type": "shomenuchi",
                "attack_variation": "",
                "name": "kaitennage",
                "name_alt": "",
                "id": 6,
                "technique_type": "projection",
                "variation": "",
                "rank": "2nd kyu",
                "notes": "",
                "translation": "",
                "opening": "offline irimi",
                "url": ""
            },
            {
                "attack_type": "shomenuchi",
                "attack_variation": "",
                "name": "koshinage",
                "name_alt": "",
                "id": 7,
                "technique_type": "projection",
                "variation": "",
                "rank": "shodan",
                "notes": "",
                "translation": "",
                "opening": "offline irimi",
                "url": ""
            },
            {
                "attack_type": "shomenuchi",
                "attack_variation": "",
                "name": "kotegaeshi",
                "name_alt": "",
                "id": 8,
                "technique_type": "projection",
                "variation": "",
                "rank": "5th kyu",
                "notes": "",
                "translation": "",
                "opening": "irimi",
                "url": ""
            },
            {
                "attack_type": "shomenuchi",
                "attack_variation": "",
                "name": "yonkyo",
                "name_alt": "",
                "id": 9,
                "technique_type": "immobilization",
                "variation": "",
                "rank": "4th kyu",
                "notes": "",
                "translation": "",
                "opening": "irimi",
                "url": ""
            },
            {
                "attack_type": "shomenuchi",
                "attack_variation": "",
                "name": "kokyunage",
                "name_alt": "",
                "id": 10,
                "technique_type": "projection",
                "variation": "kesa",
                "rank": "2nd kyu",
                "notes": "kesa – the diagonal from shoulder to hip (gi line), feign that uke will hit you and cut with other arm",
                "translation": "",
                "opening": "irimi",
                "url": "https://www.youtube.com/watch?v=z-gM1pFYSmY"
            },
            {
                "attack_type": "shomenuchi",
                "attack_variation": "",
                "name": "hijikime",
                "name_alt": "",
                "id": 11,
                "technique_type": "immobilization",
                "variation": "",
                "rank": "*",
                "notes": "",
                "translation": "",
                "opening": "irimi tenkan",
                "url": ""
            },
            {
                "attack_type": "shomenuchi",
                "attack_variation": "",
                "name": "gokyo",
                "name_alt": "",
                "id": 12,
                "technique_type": "immobilization",
                "variation": "",
                "rank": "2nd kyu",
                "notes": "",
                "translation": "",
                "opening": "irimi",
                "url": ""
            },
            {
                "attack_type": "shomenuchi",
                "attack_variation": "",
                "name": "kokyunage",
                "name_alt": "kazaguruma",
                "id": 13,
                "technique_type": "projection",
                "variation": "double cut",
                "rank": "2nd kyu",
                "notes": "",
                "translation": "",
                "opening": "irimi",
                "url": "https://www.youtube.com/watch?v=P9vfsfv3ZQg"
            },
            {
                "attack_type": "shomenuchi",
                "attack_variation": "",
                "name": "kokyunage",
                "name_alt": "",
                "id": 14,
                "technique_type": "projection",
                "variation": "",
                "rank": "*",
                "notes": "opening like ikkyo - then tenkan for wrist / elbow turn-out",
                "translation": "",
                "opening": "irimi",
                "url": "https://www.youtube.com/watch?v=P9vfsfv3ZQg"
            },
            {
                "attack_type": "shomenuchi",
                "attack_variation": "",
                "name": "kokyunage",
                "name_alt": "",
                "id": 15,
                "technique_type": "projection",
                "variation": "",
                "rank": "*",
                "notes": "opening like sankyo ura (with atemi to ribs) - then bring uke around ura and drop",
                "translation": "",
                "opening": "irimi tenkan",
                "url": "https://www.youtube.com/watch?v=P9vfsfv3ZQg"
            },
            {
                "attack_type": "shomenuchi",
                "attack_variation": "",
                "name": "kokyunage",
                "name_alt": "jujinage",
                "id": 16,
                "technique_type": "projection",
                "variation": "",
                "rank": "*",
                "notes": "step under shomen arm (with elbow atemi to face) _ tenkan and throw",
                "translation": "",
                "opening": "irimi",
                "url": "https://www.youtube.com/watch?v=P9vfsfv3ZQg"
            }
        ],
        "yokomenuchi": [
            {
                "attack_type": "yokomenuchi",
                "attack_variation": "",
                "name": "shihonage",
                "name_alt": "",
                "id": 1,
                "technique_type": "projection",
                "variation": "",
                "rank": "4th kyu",
                "notes": "",
                "translation": "",
                "opening": "step inside",
                "url": "https://www.youtube.com/watch?v=P9vfsfv3ZQg"
            },
            {
                "attack_type": "yokomenuchi",
                "attack_variation": "",
                "name": "iriminage",
                "name_alt": "",
                "id": 2,
                "technique_type": "projection",
                "variation": "",
                "rank": "3rd kyu",
                "notes": "2 ways: step in front of uke / step behind uke",
                "translation": "",
                "opening": "step inside",
                "url": "https://www.youtube.com/watch?v=eBXeLB-dMOk"
            },
            {
                "attack_type": "yokomenuchi",
                "attack_variation": "",
                "name": "iriminage",
                "name_alt": "",
                "id": 3,
                "technique_type": "projection",
                "variation": "",
                "rank": "3rd kyu",
                "notes": "same entrance as gokyo",
                "translation": "",
                "opening": "irimi",
                "url": "https://www.youtube.com/watch?v=eBXeLB-dMOk"
            },
            {
                "attack_type": "yokomenuchi",
                "attack_variation": "",
                "name": "kotegaeshi",
                "name_alt": "",
                "id": 4,
                "technique_type": "projection",
                "variation": "",
                "rank": "3rd kyu",
                "notes": "2 ways: step in front of uke / step behind uke",
                "translation": "",
                "opening": "step inside",
                "url": "https://www.youtube.com/watch?v=eBXeLB-dMOk"
            },
            {
                "attack_type": "yokomenuchi",
                "attack_variation": "",
                "name": "kotegaeshi",
                "name_alt": "",
                "id": 5,
                "technique_type": "projection",
                "variation": "",
                "rank": "3rd kyu",
                "notes": "same entrance as gokyo",
                "translation": "",
                "opening": "irimi",
                "url": "https://www.youtube.com/watch?v=eBXeLB-dMOk"
            },
            {
                "attack_type": "yokomenuchi",
                "attack_variation": "",
                "name": "gokyo",
                "name_alt": "",
                "id": 6,
                "technique_type": "immobilization",
                "variation": "",
                "rank": "3rd kyu",
                "notes": "",
                "translation": "",
                "opening": "irimi",
                "url": ""
            },
            {
                "attack_type": "yokomenuchi",
                "attack_variation": "",
                "name": "kokyunage",
                "name_alt": "",
                "id": 7,
                "technique_type": "projection",
                "variation": "",
                "rank": "*",
                "notes": "",
                "translation": "",
                "opening": "step inside",
                "url": ""
            },
            {
                "attack_type": "yokomenuchi",
                "attack_variation": "",
                "name": "kokyunage",
                "name_alt": "",
                "id": 8,
                "technique_type": "projection",
                "variation": "2 ways: block and cut / hand under elbow",
                "rank": "*",
                "notes": "step back and cut",
                "translation": "",
                "opening": "step back",
                "url": "https://www.youtube.com/watch?v=P9vfsfv3ZQg"
            },
            {
                "attack_type": "yokomenuchi",
                "attack_variation": "",
                "name": "kokyunage",
                "name_alt": "kazaguruma",
                "id": 9,
                "technique_type": "projection",
                "variation": "",
                "rank": "*",
                "notes": "direct entry: double-cut like",
                "translation": "",
                "opening": "irimi",
                "url": "https://www.youtube.com/watch?v=P9vfsfv3ZQg"
            },
            {
                "attack_type": "yokomenuchi",
                "attack_variation": "",
                "name": "hijikime",
                "name_alt": "",
                "id": 10,
                "technique_type": "immobilization",
                "variation": "",
                "rank": "*",
                "notes": "gokyo-like entry",
                "translation": "",
                "opening": "irimi",
                "url": "https://www.youtube.com/watch?v=P9vfsfv3ZQg"
            },
            {
                "attack_type": "yokomenuchi",
                "attack_variation": "",
                "name": "nikyo",
                "name_alt": "",
                "id": 11,
                "technique_type": "immobilization",
                "variation": "",
                "rank": "*",
                "notes": "gokyo-like entry",
                "translation": "",
                "opening": "irimi",
                "url": "https://www.youtube.com/watch?v=P9vfsfv3ZQg"
            },
            {
                "attack_type": "yokomenuchi",
                "attack_variation": "",
                "name": "katagatame",
                "name_alt": "",
                "id": 12,
                "technique_type": "immobilization",
                "variation": "",
                "rank": "*",
                "notes": "enter and blend letting uke's arm pass over you",
                "translation": "",
                "opening": "irimi",
                "url": "https://www.youtube.com/watch?v=P9vfsfv3ZQg"
            },
            {
                "attack_type": "yokomenuchi",
                "attack_variation": "",
                "name": "koshinage",
                "name_alt": "",
                "id": 13,
                "technique_type": "projection",
                "variation": "",
                "rank": "shodan",
                "notes": "based on shihonage",
                "translation": "",
                "opening": "step inside",
                "url": ""
            }
        ],
        "morotetori": [
            {
                "attack_type": "morotetori",
                "attack_variation": "",
                "name": "kokyunage",
                "name_alt": "kokyuho",
                "id": 0,
                "technique_type": "projection",
                "variation": "",
                "rank": "6th kyu",
                "notes": "",
                "translation": "",
                "opening": "tenkan",
                "url": ""
            },
            {
                "attack_type": "morotetori",
                "attack_variation": "",
                "name": "kokyunage",
                "name_alt": "jujinage",
                "id": 1,
                "technique_type": "projection",
                "variation": "",
                "rank": "*",
                "notes": "",
                "translation": "",
                "opening": "tenkan",
                "url": ""
            },
            {
                "attack_type": "morotetori",
                "attack_variation": "",
                "name": "kokyunage",
                "name_alt": "jujinage",
                "id": 2,
                "technique_type": "projection",
                "variation": "",
                "rank": "*",
                "notes": "enter directly in with a swooping move",
                "translation": "",
                "opening": "offline irimi",
                "url": ""
            },
            {
                "attack_type": "morotetori",
                "attack_variation": "",
                "name": "iriminage",
                "name_alt": "",
                "id": 3,
                "technique_type": "projection",
                "variation": "",
                "rank": "3rd kyu",
                "notes": "2 variations: tenkan jo, tenkan gae",
                "translation": "",
                "opening": "tenkan",
                "url": ""
            },
            {
                "attack_type": "morotetori",
                "attack_variation": "",
                "name": "iriminage",
                "name_alt": "",
                "id": 4,
                "technique_type": "projection",
                "variation": "",
                "rank": "3rd kyu",
                "notes": "enter directly in with a swooping move",
                "translation": "",
                "opening": "offline irimi",
                "url": ""
            },

            {
                "attack_type": "morotetori",
                "attack_variation": "",
                "name": "nikyo",
                "name_alt": "",
                "id": 5,
                "technique_type": "immobilization",
                "variation": "",
                "rank": "2nd kyu",
                "notes": "apply nikyo directly to 'ai-hanmi arm",
                "translation": "",
                "opening": "switch feet",
                "url": ""
            },
            {
                "attack_type": "morotetori",
                "attack_variation": "",
                "name": "nikyo",
                "name_alt": "",
                "id": 6,
                "technique_type": "immobilization",
                "variation": "",
                "rank": "2nd kyu",
                "notes": "",
                "translation": "",
                "opening": "tenkan",
                "url": ""
            },
            {
                "attack_type": "morotetori",
                "attack_variation": "",
                "name": "shihonage",
                "name_alt": "",
                "id": 7,
                "technique_type": "projection",
                "variation": "",
                "rank": "*",
                "notes": "turn hand up and uke grabs",
                "translation": "",
                "opening": "tenkan",
                "url": ""
            },
            {
                "attack_type": "morotetori",
                "attack_variation": "",
                "name": "jujinage",
                "name_alt": "",
                "id": 8,
                "technique_type": "projection",
                "variation": "",
                "rank": "*",
                "notes": "",
                "translation": "",
                "opening": "tenkan",
                "url": ""
            },
            {
                "attack_type": "morotetori",
                "attack_variation": "",
                "name": "kotegaeshi",
                "name_alt": "",
                "id": 9,
                "technique_type": "projection",
                "variation": "",
                "rank": "3rd kyu",
                "notes": "",
                "translation": "",
                "opening": "tenkan",
                "url": ""
            },
            {
                "attack_type": "morotetori",
                "attack_variation": "",
                "name": "kokyunage",
                "name_alt": "",
                "id": 10,
                "technique_type": "projection",
                "variation": "",
                "rank": "3rd kyu",
                "notes": "based on ikkyo",
                "translation": "",
                "opening": "tenkan",
                "url": ""
            },
            {
                "attack_type": "morotetori",
                "attack_variation": "",
                "name": "kokyunage",
                "name_alt": "",
                "id": 11,
                "technique_type": "projection",
                "variation": "",
                "rank": "*",
                "notes": "tenkan and project",
                "translation": "",
                "opening": "tenkan",
                "url": ""
            }
        ],
        "tsuki": [
            {
                "attack_type": "tsuki",
                "attack_variation": "",
                "name": "kotegaeshi",
                "name_alt": "",
                "id": 1,
                "technique_type": "projection",
                "variation": "",
                "rank": "5th kyu",
                "notes": "",
                "translation": "",
                "opening": "tenkan",
                "url": ""
            },
            {
                "attack_type": "tsuki",
                "attack_variation": "",
                "name": "iriminage",
                "name_alt": "",
                "id": 2,
                "technique_type": "projection",
                "variation": "",
                "rank": "4th kyu",
                "notes": "",
                "translation": "",
                "opening": "tenkan",
                "url": ""
            },
            {
                "attack_type": "tsuki",
                "attack_variation": "",
                "name": "iriminage",
                "name_alt": "",
                "id": 3,
                "technique_type": "projection",
                "variation": "",
                "rank": "4th kyu",
                "notes": "",
                "translation": "",
                "opening": "irimi",
                "url": ""
            },
            {
                "attack_type": "tsuki",
                "attack_variation": "",
                "name": "hijikime",
                "name_alt": "hijishime",
                "id": 4,
                "technique_type": "immobilization",
                "variation": "",
                "rank": "4th kyu",
                "notes": "",
                "translation": "",
                "opening": "tenkan",
                "url": ""
            },
            {
                "attack_type": "tsuki",
                "attack_variation": "",
                "name": "kaitennage",
                "name_alt": "",
                "id": 5,
                "technique_type": "projection",
                "variation": "",
                "rank": "3rd kyu",
                "notes": "",
                "translation": "",
                "opening": "offline irimi",
                "url": ""
            },

            {
                "attack_type": "tsuki",
                "attack_variation": "",
                "name": "ikkyo",
                "name_alt": "",
                "id": 6,
                "technique_type": "immobilization",
                "variation": "",
                "rank": "*",
                "notes": "",
                "translation": "step back as you swoop ukes tsuki up and into ikkyo",
                "opening": "tenshin",
                "url": ""
            },
            {
                "attack_type": "tsuki",
                "attack_variation": "",
                "name": "kokyunage",
                "name_alt": "",
                "id": 7,
                "technique_type": "projection",
                "variation": "",
                "rank": "*",
                "notes": "",
                "translation": "step in and kaiten / extend past uke's head",
                "opening": "irimi kaiten",
                "url": ""
            },
            {
                "attack_type": "tsuki",
                "attack_variation": "",
                "name": "kokyunage",
                "name_alt": "kazaguruma",
                "id": 8,
                "technique_type": "projection",
                "variation": "double-cut",
                "rank": "1st kyu",
                "notes": "double-cut",
                "translation": "",
                "opening": "step offline",
                "url": ""
            },
            {
                "attack_type": "tsuki",
                "attack_variation": "",
                "name": "kokyunage",
                "name_alt": "ushiroate",
                "id": 9,
                "technique_type": "projection",
                "variation": "",
                "rank": "1st kyu",
                "notes": "",
                "translation": "",
                "opening": "irimi tenkan",
                "url": ""
            },
            {
                "attack_type": "tsuki",
                "attack_variation": "",
                "name": "kokyunage",
                "name_alt": "",
                "id": 10,
                "technique_type": "projection",
                "variation": "draping move",
                "rank": "1st kyu",
                "notes": "",
                "translation": "",
                "opening": "offline irimi",
                "url": ""
            },
            {
                "attack_type": "tsuki",
                "attack_variation": "",
                "name": "",
                "name_alt": "",
                "id": 11,
                "technique_type": "projection",
                "variation": "",
                "rank": "4th kyu",
                "notes": "",
                "translation": "",
                "opening": "irimi",
                "url": ""
            },
            {
                "attack_type": "tsuki",
                "attack_variation": "",
                "name": "makiotoshi",
                "name_alt": "",
                "id": 12,
                "technique_type": "projection",
                "variation": "",
                "rank": "*",
                "notes": "step in and extend arm under the tsuki as you drop down",
                "translation": "",
                "opening": "step inside",
                "url": ""
            },
            {
                "attack_type": "tsuki",
                "attack_variation": "",
                "name": "kokyunage",
                "name_alt": "",
                "id": 13,
                "technique_type": "projection",
                "variation": "udegarami",
                "rank": "1st kyu",
                "notes": "",
                "translation": "",
                "opening": "irimi tenkan",
                "url": ""
            }
        ],
        "ryotetori": [
            {
                "attack_type": "ryotetori",
                "attack_variation": "",
                "name": "tenchinage",
                "name_alt": "",
                "id": 1,
                "technique_type": "projection",
                "variation": "",
                "rank": "5th kyu",
                "notes": "",
                "translation": "",
                "opening": "irimi",
                "url": ""
            },
            {
                "attack_type": "ryotetori",
                "attack_variation": "",
                "name": "kokyunage",
                "name_alt": "",
                "id": 2,
                "technique_type": "projection",
                "variation": "",
                "rank": "*",
                "notes": "",
                "translation": "",
                "opening": "tenshin",
                "url": ""
            },
            {
                "attack_type": "ryotetori",
                "attack_variation": "",
                "name": "shihonage",
                "name_alt": "",
                "id": 3,
                "technique_type": "projection",
                "variation": "",
                "rank": "3rd kyu",
                "notes": "",
                "translation": "",
                "opening": "offline irimi",
                "url": ""
            }
        ]
    }
}