{
    "aikido": [
        {
            "name": "katatetori",
            "japanese": "片手取り",
            "waza": [
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "shihonage",
                    "name_alt": "",
                    "japanese": "四方投げ",
                    "id": 1,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "6th kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "step offline",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "shihonage",
                    "name_alt": "",
                    "japanese": "四方投げ",
                    "id": 2,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "6th kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 3,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "*",
                    "notes": "reach down diagonally in front of uke and drop",
                    "translation": "",
                    "opening": "irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 4,
                    "technique_type": "projection",
                    "variation": "inside spiral",
                    "rank": "*",
                    "notes": "",
                    "translation": "",
                    "opening": "irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kokyunage",
                    "name_alt": "draping move",
                    "japanese": "呼吸投げ",
                    "id": 5,
                    "technique_type": "projection",
                    "variation": "draping move",
                    "rank": "1st kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "step offline",
                    "url": "",
                    "youtube_id": "Kt6ROzf02cI"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 6,
                    "technique_type": "projection",
                    "variation": "ki no nagare",
                    "rank": "*",
                    "notes": "step in and swoop uke's arm into yours as you break the grip, then extend past his head",
                    "translation": "",
                    "opening": "step offline",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kokyunage",
                    "name_alt": "kazaguruma",
                    "japanese": "呼吸投げ",
                    "id": 7,
                    "technique_type": "projection",
                    "variation": "double cut",
                    "rank": "*",
                    "notes": "",
                    "translation": "",
                    "opening": "step offline",
                    "url": "",
                    "youtube_id": "Kt6ROzf02cI"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kokyunage",
                    "name_alt": "jujinage",
                    "japanese": "呼吸投げ",
                    "id": 8,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "*",
                    "notes": "",
                    "translation": "",
                    "opening": "tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 9,
                    "technique_type": "projection",
                    "variation": "into back roll / breakfall",
                    "rank": "*",
                    "notes": "extend hand down and behind uke, to unballance them",
                    "translation": "",
                    "opening": "offline irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 10,
                    "technique_type": "projection",
                    "variation": "into forward roll",
                    "rank": "5th kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 11,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "*",
                    "notes": "like sumiotoshi into a forward roll",
                    "translation": "corner drop",
                    "opening": "switch feet",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "sumiotoshi",
                    "name_alt": "",
                    "japanese": "角落し",
                    "id": 12,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "2nd kyu",
                    "notes": "",
                    "translation": "corner drop",
                    "opening": "tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "sumiotoshi",
                    "name_alt": "",
                    "japanese": "角落し",
                    "id": 13,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "2nd kyu",
                    "notes": "",
                    "translation": "corner drop",
                    "opening": "offline irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "iriminage",
                    "name_alt": "",
                    "japanese": "入身投げ",
                    "id": 14,
                    "technique_type": "projection",
                    "variation": "jo",
                    "rank": "6th kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "offline irimi",
                    "url": "",
                    "youtube_id": "Kt6ROzf02cI"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "nikyo",
                    "name_alt": "",
                    "japanese": "二教",
                    "id": 15,
                    "technique_type": "immobilization",
                    "variation": "swooping move",
                    "rank": "4th kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "step offline",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "nikyo",
                    "name_alt": "",
                    "japanese": "二教",
                    "id": 16,
                    "technique_type": "immobilization",
                    "variation": "w/ atemi",
                    "rank": "*",
                    "notes": "cut ukes arm at the elbow, as you step in place, then tenkan",
                    "translation": "",
                    "opening": "switch feet",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "nikyo",
                    "name_alt": "",
                    "japanese": "二教",
                    "id": 17,
                    "technique_type": "immobilization",
                    "variation": "",
                    "rank": "4th kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kotegaeshi",
                    "name_alt": "",
                    "japanese": "小手返し",
                    "id": 18,
                    "technique_type": "projection",
                    "variation": "reverse kotegaeshi",
                    "rank": "*",
                    "notes": "",
                    "translation": "",
                    "opening": "switch feet",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kotegaeshi",
                    "name_alt": "",
                    "japanese": "小手返し",
                    "id": 19,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "6th kyu",
                    "notes": "basic",
                    "translation": "",
                    "opening": "tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "koshinage",
                    "name_alt": "",
                    "japanese": "腰投げ",
                    "id": 20,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "3rd kyu",
                    "notes": "atemi as you step inside and turn, making a chair of your lower back to lower uke over",
                    "translation": "",
                    "opening": "switch feet",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "hijikime",
                    "name_alt": "",
                    "japanese": "?",
                    "id": 21,
                    "technique_type": "immobilization",
                    "variation": "swopping move",
                    "rank": "*",
                    "notes": "",
                    "translation": "",
                    "opening": "tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "hiji waza",
                    "name_alt": "arm bar",
                    "japanese": "?",
                    "id": 22,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "*",
                    "notes": "step to the side and lower the grabbed hand, while bracing uke's elbow with the other",
                    "translation": "",
                    "opening": "step offline",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "ushiro ate",
                    "name_alt": "",
                    "japanese": "?",
                    "id": 23,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "*",
                    "notes": "",
                    "translation": "",
                    "opening": "offline irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "ikkyo",
                    "name_alt": "",
                    "japanese": "一教",
                    "id": 24,
                    "technique_type": "immobilization",
                    "variation": "",
                    "rank": "5th kyu",
                    "notes": "Yamada style",
                    "translation": "",
                    "opening": "tenkan",
                    "url": "",
                    "youtube_id": "Kt6ROzf02cI"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "ikkyo",
                    "name_alt": "",
                    "japanese": "一教",
                    "id": 25,
                    "technique_type": "immobilization",
                    "variation": "swooping move",
                    "rank": "5th kyu",
                    "notes": "tenzan style(?)",
                    "translation": "",
                    "opening": "step offline",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "sankyo",
                    "name_alt": "",
                    "japanese": "三教",
                    "id": 26,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "*",
                    "notes": "Yamada style",
                    "translation": "",
                    "opening": "tenkan",
                    "url": "",
                    "youtube_id": "Kt6ROzf02cI"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "katagatame",
                    "name_alt": "",
                    "japanese": "?",
                    "id": 27,
                    "technique_type": "immobilization",
                    "variation": "",
                    "rank": "1st kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kaitennage",
                    "name_alt": "",
                    "japanese": "回転投げ",
                    "id": 28,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "4th kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "offline irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "aikiotoshi",
                    "name_alt": "",
                    "japanese": "?落し",
                    "id": 29,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "*",
                    "notes": "",
                    "translation": "",
                    "opening": "step offline",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"}
                , 
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "makiotoshi",
                    "name_alt": "",
                    "japanese": "?落し",
                    "id": 30,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "*",
                    "notes": "",
                    "translation": "",
                    "opening": "step inside",
                    "url": "",
                    "youtube_id": "VtjNiohlH5Q"
                }
            ]
        },
        {
            "name": "shomenuchi",
            "japanese": "正面打ち",
            "waza": [
                {
                    "attack_type": "shomenuchi",
                    "attack_variation": "",
                    "name": "ikkyo",
                    "name_alt": "",
                    "japanese": "一教",
                    "id": 1,
                    "technique_type": "immobilization",
                    "variation": "omote",
                    "rank": "5th kyu",
                    "notes": "",
                    "translation": "1st technique",
                    "opening": "irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "shomenuchi",
                    "attack_variation": "",
                    "name": "iriminage",
                    "name_alt": "",
                    "japanese": "入身投げ",
                    "id": 2,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "5th kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "offline irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "shomenuchi",
                    "attack_variation": "",
                    "name": "nikyo",
                    "name_alt": "",
                    "japanese": "二教",
                    "id": 3,
                    "technique_type": "immobilization",
                    "variation": "ura",
                    "rank": "4th kyu",
                    "notes": "same opening as kaiten nage",
                    "translation": "",
                    "opening": "offline irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "shomenuchi",
                    "attack_variation": "",
                    "name": "sankyo",
                    "name_alt": "",
                    "japanese": "三教",
                    "id": 4,
                    "technique_type": "immobilization",
                    "variation": "omote",
                    "rank": "3rd kyu",
                    "notes": "ikkyo opening – then switch to sankyo",
                    "translation": "",
                    "opening": "irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "shomenuchi",
                    "attack_variation": "",
                    "name": "shihonage",
                    "name_alt": "",
                    "japanese": "四方投げ",
                    "id": 5,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "2nd kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "shomenuchi",
                    "attack_variation": "",
                    "name": "kaitennage",
                    "name_alt": "",
                    "japanese": "回転投げ",
                    "id": 6,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "2nd kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "offline irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "shomenuchi",
                    "attack_variation": "",
                    "name": "koshinage",
                    "name_alt": "",
                    "japanese": "腰投げ",
                    "id": 7,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "shodan",
                    "notes": "",
                    "translation": "",
                    "opening": "offline irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "shomenuchi",
                    "attack_variation": "",
                    "name": "kotegaeshi",
                    "name_alt": "",
                    "japanese": "小手返し",
                    "id": 8,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "5th kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "shomenuchi",
                    "attack_variation": "",
                    "name": "yonkyo",
                    "name_alt": "",
                    "japanese": "四教",
                    "id": 9,
                    "technique_type": "immobilization",
                    "variation": "",
                    "rank": "4th kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "shomenuchi",
                    "attack_variation": "",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 10,
                    "technique_type": "projection",
                    "variation": "kesa",
                    "rank": "2nd kyu",
                    "notes": "kesa – the diagonal from shoulder to hip (gi line), feign that uke will hit you and cut with other arm",
                    "translation": "",
                    "opening": "irimi",
                    "url": "",
                    "youtube_id": "z-gM1pFYSmY"
                },
                {
                    "attack_type": "shomenuchi",
                    "attack_variation": "",
                    "name": "hijikime",
                    "name_alt": "",
                    "japanese": "?",
                    "id": 11,
                    "technique_type": "immobilization",
                    "variation": "",
                    "rank": "*",
                    "notes": "",
                    "translation": "",
                    "opening": "irimi tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "shomenuchi",
                    "attack_variation": "",
                    "name": "gokyo",
                    "name_alt": "",
                    "japanese": "五教",
                    "id": 12,
                    "technique_type": "immobilization",
                    "variation": "",
                    "rank": "2nd kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "shomenuchi",
                    "attack_variation": "",
                    "name": "kokyunage",
                    "name_alt": "kazaguruma",
                    "japanese": "呼吸投げ",
                    "id": 13,
                    "technique_type": "projection",
                    "variation": "double cut",
                    "rank": "2nd kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "shomenuchi",
                    "attack_variation": "",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 14,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "*",
                    "notes": "opening like ikkyo - then tenkan for wrist / elbow turn-out",
                    "translation": "",
                    "opening": "irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "shomenuchi",
                    "attack_variation": "",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 15,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "*",
                    "notes": "opening like sankyo ura (with atemi to ribs) - then bring uke around ura and drop",
                    "translation": "",
                    "opening": "irimi tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "shomenuchi",
                    "attack_variation": "",
                    "name": "kokyunage",
                    "name_alt": "jujinage",
                    "japanese": "呼吸投げ",
                    "id": 16,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "*",
                    "notes": "step under shomen arm (with elbow atemi to face) _ tenkan and throw",
                    "translation": "",
                    "opening": "irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                }
            ]
        },
        {
            "name": "yokomenuchi",
            "japanese": "横面打ち",
            "waza": [
                {
                    "attack_type": "yokomenuchi",
                    "attack_variation": "",
                    "name": "shihonage",
                    "name_alt": "",
                    "japanese": "四方投げ",
                    "id": 1,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "4th kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "step inside",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "yokomenuchi",
                    "attack_variation": "",
                    "name": "iriminage",
                    "name_alt": "",
                    "japanese": "入身投げ",
                    "id": 2,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "3rd kyu",
                    "notes": "2 ways: step in front of uke / step behind uke",
                    "translation": "",
                    "opening": "step inside",
                    "url": "",
                    "youtube_id": "eBXeLB-dMOk"
                },
                {
                    "attack_type": "yokomenuchi",
                    "attack_variation": "",
                    "name": "iriminage",
                    "name_alt": "",
                    "japanese": "入身投げ",
                    "id": 3,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "3rd kyu",
                    "notes": "same entrance as gokyo",
                    "translation": "",
                    "opening": "irimi",
                    "url": "",
                    "youtube_id": "eBXeLB-dMOk"
                },
                {
                    "attack_type": "yokomenuchi",
                    "attack_variation": "",
                    "name": "kotegaeshi",
                    "name_alt": "",
                    "japanese": "小手返し",
                    "id": 4,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "3rd kyu",
                    "notes": "2 ways: step in front of uke / step behind uke",
                    "translation": "",
                    "opening": "step inside",
                    "url": "",
                    "youtube_id": "eBXeLB-dMOk"
                },
                {
                    "attack_type": "yokomenuchi",
                    "attack_variation": "",
                    "name": "kotegaeshi",
                    "name_alt": "",
                    "japanese": "小手返し",
                    "id": 5,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "3rd kyu",
                    "notes": "same entrance as gokyo",
                    "translation": "",
                    "opening": "irimi",
                    "url": "",
                    "youtube_id": "eBXeLB-dMOk"
                },
                {
                    "attack_type": "yokomenuchi",
                    "attack_variation": "",
                    "name": "gokyo",
                    "name_alt": "",
                    "japanese": "五教",
                    "id": 6,
                    "technique_type": "immobilization",
                    "variation": "",
                    "rank": "3rd kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "yokomenuchi",
                    "attack_variation": "",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 7,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "*",
                    "notes": "",
                    "translation": "",
                    "opening": "step inside",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "yokomenuchi",
                    "attack_variation": "",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 8,
                    "technique_type": "projection",
                    "variation": "2 ways: block and cut / hand under elbow",
                    "rank": "*",
                    "notes": "step back and cut",
                    "translation": "",
                    "opening": "step back",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "yokomenuchi",
                    "attack_variation": "",
                    "name": "kokyunage",
                    "name_alt": "kazaguruma",
                    "japanese": "呼吸投げ",
                    "id": 9,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "*",
                    "notes": "direct entry: double-cut like",
                    "translation": "",
                    "opening": "irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "yokomenuchi",
                    "attack_variation": "",
                    "name": "hijikime",
                    "name_alt": "",
                    "japanese": "?",
                    "id": 10,
                    "technique_type": "immobilization",
                    "variation": "",
                    "rank": "*",
                    "notes": "gokyo-like entry",
                    "translation": "",
                    "opening": "irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "yokomenuchi",
                    "attack_variation": "",
                    "name": "nikyo",
                    "name_alt": "",
                    "japanese": "二教",
                    "id": 11,
                    "technique_type": "immobilization",
                    "variation": "",
                    "rank": "*",
                    "notes": "gokyo-like entry",
                    "translation": "",
                    "opening": "irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "yokomenuchi",
                    "attack_variation": "",
                    "name": "katagatame",
                    "name_alt": "",
                    "japanese": "?",
                    "id": 12,
                    "technique_type": "immobilization",
                    "variation": "",
                    "rank": "*",
                    "notes": "enter and blend letting uke's arm pass over you",
                    "translation": "",
                    "opening": "irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "yokomenuchi",
                    "attack_variation": "",
                    "name": "koshinage",
                    "name_alt": "",
                    "japanese": "腰投げ",
                    "id": 13,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "shodan",
                    "notes": "based on shihonage",
                    "translation": "",
                    "opening": "step inside", 
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                }
            ]
        },
        {
            "name": "morotetori",
            "japanese": "",
            "waza": [
                {
                    "attack_type": "morotetori",
                    "attack_variation": "",
                    "name": "kokyunage",
                    "name_alt": "kokyuho",
                    "japanese": "呼吸投げ",
                    "id": 0,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "6th kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "morotetori",
                    "attack_variation": "",
                    "name": "kokyunage",
                    "name_alt": "jujinage",
                    "japanese": "呼吸投げ",
                    "id": 1,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "*",
                    "notes": "",
                    "translation": "",
                    "opening": "tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "morotetori",
                    "attack_variation": "",
                    "name": "kokyunage",
                    "name_alt": "jujinage",
                    "japanese": "呼吸投げ",
                    "id": 2,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "*",
                    "notes": "enter directly in with a swooping move",
                    "translation": "",
                    "opening": "offline irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "morotetori",
                    "attack_variation": "",
                    "name": "iriminage",
                    "name_alt": "",
                    "japanese": "入身投げ",
                    "id": 3,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "3rd kyu",
                    "notes": "2 variations: tenkan jo, tenkan gae",
                    "translation": "",
                    "opening": "tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "morotetori",
                    "attack_variation": "",
                    "name": "iriminage",
                    "name_alt": "",
                    "japanese": "入身投げ",
                    "id": 4,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "3rd kyu",
                    "notes": "enter directly in with a swooping move",
                    "translation": "",
                    "opening": "offline irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },

                {
                    "attack_type": "morotetori",
                    "attack_variation": "",
                    "name": "nikyo",
                    "name_alt": "",
                    "japanese": "二教",
                    "id": 5,
                    "technique_type": "immobilization",
                    "variation": "",
                    "rank": "2nd kyu",
                    "notes": "apply nikyo directly to 'ai-hanmi arm",
                    "translation": "",
                    "opening": "switch feet",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "morotetori",
                    "attack_variation": "",
                    "name": "nikyo",
                    "name_alt": "",
                    "japanese": "二教",
                    "id": 6,
                    "technique_type": "immobilization",
                    "variation": "",
                    "rank": "2nd kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "morotetori",
                    "attack_variation": "",
                    "name": "shihonage",
                    "name_alt": "",
                    "japanese": "四方投げ",
                    "id": 7,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "*",
                    "notes": "turn hand up and uke grabs",
                    "translation": "",
                    "opening": "tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "morotetori",
                    "attack_variation": "",
                    "name": "jujinage",
                    "name_alt": "",
                    "japanese": "十字投げ",
                    "id": 8,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "*",
                    "notes": "",
                    "translation": "",
                    "opening": "tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "morotetori",
                    "attack_variation": "",
                    "name": "kotegaeshi",
                    "name_alt": "",
                    "japanese": "小手返し",
                    "id": 9,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "3rd kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "morotetori",
                    "attack_variation": "",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 10,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "3rd kyu",
                    "notes": "based on ikkyo",
                    "translation": "",
                    "opening": "tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "morotetori",
                    "attack_variation": "",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 11,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "*",
                    "notes": "tenkan and project",
                    "translation": "",
                    "opening": "tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                }
            ]
        },
        {
            "name": "tsuki",
            "japanese": "",
            "waza": [
                {
                    "attack_type": "tsuki",
                    "attack_variation": "",
                    "name": "kotegaeshi",
                    "name_alt": "",
                    "japanese": "小手返し",
                    "id": 1,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "5th kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "tsuki",
                    "attack_variation": "",
                    "name": "iriminage",
                    "name_alt": "",
                    "japanese": "入身投げ",
                    "id": 2,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "4th kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "tsuki",
                    "attack_variation": "",
                    "name": "iriminage",
                    "name_alt": "",
                    "japanese": "入身投げ",
                    "id": 3,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "4th kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "tsuki",
                    "attack_variation": "",
                    "name": "hijikime",
                    "name_alt": "hijishime",
                    "japanese": "?",
                    "id": 4,
                    "technique_type": "immobilization",
                    "variation": "",
                    "rank": "4th kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "tsuki",
                    "attack_variation": "",
                    "name": "kaitennage",
                    "name_alt": "",
                    "japanese": "回転投げ",
                    "id": 5,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "3rd kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "offline irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },

                {
                    "attack_type": "tsuki",
                    "attack_variation": "",
                    "name": "ikkyo",
                    "name_alt": "",
                    "japanese": "一教",
                    "id": 6,
                    "technique_type": "immobilization",
                    "variation": "",
                    "rank": "*",
                    "notes": "",
                    "translation": "step back as you swoop ukes tsuki up and into ikkyo",
                    "opening": "tenshin",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "tsuki",
                    "attack_variation": "",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 7,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "*",
                    "notes": "",
                    "translation": "step in and kaiten / extend past uke's head",
                    "opening": "irimi kaiten",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "tsuki",
                    "attack_variation": "",
                    "name": "kokyunage",
                    "name_alt": "kazaguruma",
                    "japanese": "呼吸投げ",
                    "id": 8,
                    "technique_type": "projection",
                    "variation": "double-cut",
                    "rank": "1st kyu",
                    "notes": "double-cut",
                    "translation": "",
                    "opening": "step offline",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "tsuki",
                    "attack_variation": "",
                    "name": "kokyunage",
                    "name_alt": "ushiroate",
                    "japanese": "呼吸投げ",
                    "id": 9,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "1st kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "irimi tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "tsuki",
                    "attack_variation": "",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 10,
                    "technique_type": "projection",
                    "variation": "draping move",
                    "rank": "1st kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "offline irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "tsuki",
                    "attack_variation": "",
                    "name": "iriminage",
                    "name_alt": "",
                    "japanese": "入身投げ",
                    "id": 11,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "4th kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "tsuki",
                    "attack_variation": "",
                    "name": "makiotoshi",
                    "name_alt": "",
                    "japanese": "?落し",
                    "id": 12,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "*",
                    "notes": "step in and extend arm under the tsuki as you drop down",
                    "translation": "",
                    "opening": "step inside",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "tsuki",
                    "attack_variation": "",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 13,
                    "technique_type": "projection",
                    "variation": "udegarami",
                    "rank": "1st kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "irimi tenkan",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                }
            ]
        },
        {
            "name": "ryotetori",
            "japanese": "",
            "waza": [
                {
                    "attack_type": "ryotetori",
                    "attack_variation": "",
                    "name": "tenchinage",
                    "name_alt": "",
                    "japanese": "天地投げ",
                    "id": 1,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "5th kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "ryotetori",
                    "attack_variation": "",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 2,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "*",
                    "notes": "",
                    "translation": "",
                    "opening": "tenshin",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                },
                {
                    "attack_type": "ryotetori",
                    "attack_variation": "",
                    "name": "shihonage",
                    "name_alt": "",
                    "japanese": "四方投げ",
                    "id": 3,
                    "technique_type": "projection",
                    "variation": "",
                    "rank": "3rd kyu",
                    "notes": "",
                    "translation": "",
                    "opening": "offline irimi",
                    "url": "",
                    "youtube_id": "P9vfsfv3ZQg"
                }
            ]
        }
    ]
}