{
    "aikido": [
        {
            "name": "katatetori",
            "japanese": "片手取り",
            "waza": [
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "shihonage",
                    "name_alt": "",
                    "japanese": "四方投げ",
                    "id": 1,
                    "technique_type": "projection",
                    "direction": "omote",
                    "rank": "6th kyu",
                    "notes": "",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "chudan grab",
                    "youtube_id": "_MPwI4RmHeU&t=5m12s"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "shihonage",
                    "name_alt": "",
                    "japanese": "四方投げ",
                    "id": 2,
                    "technique_type": "projection",
                    "direction": "tenkan",
                    "rank": "6th kyu",
                    "notes": "",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "chudan grab",
                    "youtube_id": "_MPwI4RmHeU&t=7m12s"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kokyunage",
                    "name_alt": "inside spiral",
                    "japanese": "呼吸投げ",
                    "id": 3,
                    "technique_type": "projection",
                    "direction": "inside spiral",
                    "rank": "5th kyu",
                    "notes": "",
                    "translation": "",
                    "foot_movement": "none",
                    "hand_movement": "jodan kokyu",
                    "youtube_id": "aiS6LPv06Xs"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name_alt": "kokyunage",
                    "name": "udekimenage",
                    "japanese": "呼吸投げ",
                    "id": 4,
                    "technique_type": "projection",
                    "direction": "tenkan",
                    "rank": "4th kyu",
                    "notes": "Tenzan name: jujinage",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "chudan grab",
                    "youtube_id": "X5mL7Fy3i6w&t=52s"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 5,
                    "technique_type": "projection",
                    "direction": "tenkan",
                    "rank": "5th kyu",
                    "notes": "into forward roll",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "chudan kokyu",
                    "youtube_id": "LJzwh22prCo"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "iriminage",
                    "name_alt": "",
                    "japanese": "入身投げ",
                    "id": 6,
                    "technique_type": "projection",
                    "direction": "tenkan",
                    "rank": "6th kyu",
                    "notes": "jodan",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "gedan cut",
                    "youtube_id": "Kt6ROzf02cI&t=5s"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "nikyo",
                    "name_alt": "",
                    "japanese": "二教",
                    "id": 7,
                    "technique_type": "immobilization",
                    "direction": "",
                    "rank": "4th kyu",
                    "notes": "",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "jodan atemi",
                    "youtube_id": "ummLn3M_Sk8&t=1m7s"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kotegaeshi",
                    "name_alt": "",
                    "japanese": "小手返し",
                    "id": 8,
                    "technique_type": "projection",
                    "direction": "tenkan",
                    "rank": "6th kyu",
                    "notes": "basic",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "gedan cut",
                    "youtube_id": "O5ozbOKbl68"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "ikkyo",
                    "name_alt": "swooping move",
                    "japanese": "一教",
                    "id": 9,
                    "technique_type": "immobilization",
                    "direction": "omote",
                    "rank": "5th kyu",
                    "notes": "tenzan style(?)",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "chudan cut",
                    "youtube_id": "1XlhMk5nvGU"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 10,
                    "technique_type": "projection",
                    "direction": "tenkan",
                    "rank": "*",
                    "notes": "Yamada style - bring uke around as you drop, then extend past uke's head",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "chudan kokyu",
                    "youtube_id": "Kt6ROzf02cI&t=45s"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kaitennage",
                    "name_alt": "",
                    "japanese": "回転投げ",
                    "id": 11,
                    "technique_type": "projection",
                    "direction": "",
                    "rank": "4th kyu",
                    "notes": "irimi tenkan",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "gedan kokyu",
                    "youtube_id": "gqvZ4KzIESw&t=21s"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "katagatame",
                    "name_alt": "",
                    "japanese": "回転投げ",
                    "id": 12,
                    "technique_type": "projection",
                    "direction": "",
                    "rank": "4th kyu",
                    "notes": "irimi tenkan",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "gedan kokyu",
                    "youtube_id": "gqvZ4KzIESw&t=21s"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 13,
                    "technique_type": "projection",
                    "direction": "",
                    "rank": "1st kyu",
                    "notes": "reach down diagonally in front of uke and drop",
                    "translation": "",
                    "foot_movement": "turn inside",
                    "hand_movement": "gedan kokyu",
                    "youtube_id": ""
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kokyunage",
                    "name_alt": "draping move",
                    "japanese": "呼吸投げ",
                    "id": 14,
                    "technique_type": "projection",
                    "direction": "draping move",
                    "rank": "1st kyu",
                    "notes": "",
                    "translation": "",
                    "foot_movement": "ayumi ashi",
                    "hand_movement": "jodan kokyu",
                    "youtube_id": "Kt6ROzf02cI&t=35s"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kokyunage",
                    "name_alt": "",
                    "japanese": "呼吸投げ",
                    "id": 15,
                    "technique_type": "projection",
                    "direction": "ki no nagare",
                    "rank": "3rd kyu",
                    "notes": "direct entry: quickly extend past uke head",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "jodan kokyu",
                    "youtube_id": ""
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kokyunage",
                    "name_alt": "kazaguruma",
                    "japanese": "呼吸投げ",
                    "id": 16,
                    "technique_type": "projection",
                    "direction": "",
                    "rank": "1st kyu",
                    "notes": "double cut",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "gedan cut",
                    "youtube_id": "Kt6ROzf02cI"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kokyunage",
                    "name_alt": "sumiotoshi-like",
                    "japanese": "呼吸投げ",
                    "id": 17,
                    "technique_type": "projection",
                    "direction": "offline irimi",
                    "rank": "1st kyu",
                    "notes": "extend hand down and behind uke, to unballance them into back roll / breakfall",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "gedan kokyu",
                    "youtube_id": "KyRnlnk4dU4"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "sumiotoshi",
                    "name_alt": "",
                    "japanese": "角落し",
                    "id": 18,
                    "technique_type": "projection",
                    "direction": "tenkan",
                    "rank": "2nd kyu",
                    "notes": "",
                    "translation": "corner drop",
                    "foot_movement": "offline step",
                    "hand_movement": "chudan kokyu",
                    "youtube_id": "zDgjNFsVq6Y&t=8s"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "sumiotoshi",
                    "name_alt": "",
                    "japanese": "角落し",
                    "id": 19,
                    "technique_type": "projection",
                    "direction": "irimi",
                    "rank": "2nd kyu",
                    "notes": "",
                    "translation": "corner drop",
                    "foot_movement": "offline step",
                    "hand_movement": "gedan kokyu",
                    "youtube_id": "m9qyncOTzRg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "nikyo",
                    "name_alt": "",
                    "japanese": "二教",
                    "id": 20,
                    "technique_type": "immobilization",
                    "direction": "",
                    "rank": "2nd kyu",
                    "notes": "cut ukes arm at the elbow, as you step in place, then tenkan",
                    "translation": "",
                    "foot_movement": "inside step",
                    "hand_movement": "jodan atemi",
                    "youtube_id": "-xj11RYo7Vg"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kotegaeshi",
                    "name_alt": "",
                    "japanese": "小手返し",
                    "id": 21,
                    "technique_type": "projection",
                    "direction": "reverse kotegaeshi",
                    "rank": "2nd kyu",
                    "notes": "",
                    "translation": "",
                    "foot_movement": "tenshin",
                    "hand_movement": "jodan grab",
                    "youtube_id": "Gw6hSmZ9WHY&t=8s"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "koshinage",
                    "name_alt": "",
                    "japanese": "腰投げ",
                    "id": 22,
                    "technique_type": "projection",
                    "direction": "",
                    "rank": "3rd kyu",
                    "notes": "atemi as you step inside and turn, making a chair of your lower back to lower uke over",
                    "translation": "",
                    "foot_movement": "inside step",
                    "hand_movement": "jodan kokyu",
                    "youtube_id": "Kt6ROzf02cI&t=3m6s"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "hijikime",
                    "name_alt": "",
                    "japanese": "?",
                    "id": 23,
                    "technique_type": "immobilization",
                    "direction": "tenkan",
                    "rank": "1st kyu",
                    "notes": "swopping move",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "jodan grab",
                    "youtube_id": "mjbZDCkIZeU&t=28s"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "hijinage",
                    "name_alt": "arm bar",
                    "japanese": "?",
                    "id": 24,
                    "technique_type": "projection",
                    "direction": "",
                    "rank": "1st kyu",
                    "notes": "step to the side and lower the grabbed hand, while bracing uke's elbow with the other",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "chudan grab",
                    "youtube_id": "mjbZDCkIZeU&t=2m32s"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "ushiro ate",
                    "name_alt": "",
                    "japanese": "?",
                    "id": 25,
                    "technique_type": "projection",
                    "direction": "tenkan",
                    "rank": "2nd kyu",
                    "notes": "",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "gedan cut",
                    "youtube_id": ""
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "ikkyo",
                    "name_alt": "",
                    "japanese": "一教",
                    "id": 26,
                    "technique_type": "immobilization",
                    "direction": "tenkan",
                    "rank": "5th kyu",
                    "notes": "Yamada style",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "chudan kokyu",
                    "youtube_id": "Kt6ROzf02cI&t=1m"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "nikyo",
                    "name_alt": "",
                    "japanese": "",
                    "id": 27,
                    "technique_type": "immobilization",
                    "direction": "tenkan",
                    "rank": "1st kyu",
                    "notes": "Yamada style",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "chudan kokyu",
                    "youtube_id": "Kt6ROzf02cI&t=1m17s"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "sankyo",
                    "name_alt": "",
                    "japanese": "三教",
                    "id": 28,
                    "technique_type": "projection",
                    "direction": "tenkan",
                    "rank": "1st kyu",
                    "notes": "Yamada style",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "chudan kokyu",
                    "youtube_id": "Kt6ROzf02cI"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "katagatame",
                    "name_alt": "",
                    "japanese": "?",
                    "id": 29,
                    "technique_type": "immobilization",
                    "direction": "tenkan",
                    "rank": "1st kyu",
                    "notes": "like kaiten but an arm pin",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "chudan kokyu",
                    "youtube_id": "d5rFtHm0LSE"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kaitennage",
                    "name_alt": "",
                    "japanese": "?",
                    "id": 30,
                    "technique_type": "immobilization",
                    "direction": "tenkan",
                    "rank": "1st kyu",
                    "notes": "",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "chudan kokyu",
                    "youtube_id": "d5rFtHm0LSE"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "aikiotoshi",
                    "name_alt": "",
                    "japanese": "?落し",
                    "id": 31,
                    "technique_type": "projection",
                    "direction": "",
                    "rank": "1st kyu",
                    "notes": "",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "chudan grab",
                    "youtube_id": "uEEV-ZzoWgo&t=1m43s"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "makiotoshi",
                    "name_alt": "",
                    "japanese": "?落し",
                    "id": 32,
                    "technique_type": "projection",
                    "direction": "",
                    "rank": "1st kyu",
                    "notes": "",
                    "translation": "",
                    "foot_movement": "tenshin",
                    "hand_movement": "gedan kokyu",
                    "youtube_id": "VtjNiohlH5Q"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "kotegaeshi",
                    "name_alt": "",
                    "japanese": "?落し",
                    "id": 33,
                    "technique_type": "projection",
                    "direction": "",
                    "rank": "1st kyu",
                    "notes": "step back and cut at uke's elbow then tenkan",
                    "translation": "",
                    "foot_movement": "tenshin",
                    "hand_movement": "gedan cut",
                    "youtube_id": ""
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "iriminage",
                    "name_alt": "",
                    "japanese": "?落し",
                    "id": 34,
                    "technique_type": "projection",
                    "direction": "",
                    "rank": "1st kyu",
                    "notes": "step back and cut at uke's elbow then enter behind",
                    "translation": "",
                    "foot_movement": "tenshin",
                    "hand_movement": "gedan cut",
                    "youtube_id": ""
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "shihonage",
                    "name_alt": "",
                    "japanese": "?落し",
                    "id": 35,
                    "technique_type": "projection",
                    "direction": "",
                    "rank": "1st kyu",
                    "notes": "step back and cut at uke's elbow",
                    "translation": "",
                    "foot_movement": "tenshin",
                    "hand_movement": "jodan cut",
                    "youtube_id": ""
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "sankyo",
                    "name_alt": "swooping move",
                    "japanese": "一教",
                    "id": 36,
                    "technique_type": "immobilization",
                    "direction": "omote",
                    "rank": "5th kyu",
                    "notes": "open with ikkyo then get sankyo grip",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "chudan cut",
                    "youtube_id": "1XlhMk5nvGU"
                },
                {
                    "attack_type": "katatetori",
                    "attack_variation": "gyaku hanmi",
                    "name": "sankyo",
                    "name_alt": "Nishio's Choke",
                    "japanese": "一教",
                    "id": 37,
                    "technique_type": "immobilization",
                    "direction": "omote",
                    "rank": "1st dan",
                    "notes": "starts like kaitennage then spin uke for a choke",
                    "translation": "",
                    "foot_movement": "offline step",
                    "hand_movement": "chudan cut",
                    "youtube_id": ""
                }
            ]
        }
    ]
}